# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 681)
        MainWindow.setStyleSheet("background-color: rgb(220, 250, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgba(158, 158, 158,100);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(120, 120, 120);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    padding: 5px 5px 5px 5px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border-radius:10px;\n"
"    background-color: rgba(70, 70, 70, 200);\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 5px 5px 5px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 5px 5px 5px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgba(60, 60, 60, 200);\n"
"}")
        self.pushButton_8.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/slide_menu/icons/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_6.addWidget(self.pushButton_8)
        self.horizontalLayout.addWidget(self.frame_7)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(80, 80, 80);\n"
"    border-bottom: 5px solid rgb(80, 80, 80);\n"
"    background-color: rgba(100, 100, 100, 200);\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(100, 100, 100);\n"
"    border-bottom: 5px solid rgb(100, 100, 100);\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(100, 100, 100);\n"
"    border-bottom: 5px solid rgb(100, 100, 100);\n"
"    background-color: rgba(80, 80, 80, 200);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(80, 80, 80);\n"
"    border-bottom: 5px solid rgb(80, 80, 80);\n"
"    background-color: rgba(100, 100, 100, 200);\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(100, 100, 100);\n"
"    border-bottom: 5px solid rgb(100, 100, 100);\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(100, 100, 100);\n"
"    border-bottom: 5px solid rgb(100, 100, 100);\n"
"    background-color: rgba(80, 80, 80, 200);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(80, 80, 80);\n"
"    border-bottom: 5px solid rgb(80, 80, 80);\n"
"    background-color: rgba(100, 100, 100, 200);\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(100, 100, 100);\n"
"    border-bottom: 5px solid rgb(100, 100, 100);\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(100, 100, 100);\n"
"    border-bottom: 5px solid rgb(100, 100, 100);\n"
"    background-color: rgba(80, 80, 80, 200);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(80, 80, 80);\n"
"    border-bottom: 5px solid rgb(80, 80, 80);\n"
"    background-color: rgba(100, 100, 100, 200);\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(100, 100, 100);\n"
"    border-bottom: 5px solid rgb(100, 100, 100);\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(100, 100, 100);\n"
"    border-bottom: 5px solid rgb(100, 100, 100);\n"
"    background-color: rgba(80, 80, 80, 200);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimize_window_button = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimize_window_button.sizePolicy().hasHeightForWidth())
        self.minimize_window_button.setSizePolicy(sizePolicy)
        self.minimize_window_button.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    padding: 5px 5px 5px 5px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgba(100, 100, 100, 200);\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 5px 5px 5px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 5px 5px 5px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgba(60, 60, 60, 200);\n"
"}")
        self.minimize_window_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/window/icons/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_window_button.setIcon(icon1)
        self.minimize_window_button.setIconSize(QtCore.QSize(18, 18))
        self.minimize_window_button.setObjectName("minimize_window_button")
        self.horizontalLayout_2.addWidget(self.minimize_window_button)
        self.restore_window_button = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restore_window_button.sizePolicy().hasHeightForWidth())
        self.restore_window_button.setSizePolicy(sizePolicy)
        self.restore_window_button.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    padding: 5px 5px 5px 5px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgba(100, 100, 100, 200);\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 5px 5px 5px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 5px 5px 5px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgba(60, 60, 60, 200);\n"
"}")
        self.restore_window_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/window/icons/fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restore_window_button.setIcon(icon2)
        self.restore_window_button.setObjectName("restore_window_button")
        self.horizontalLayout_2.addWidget(self.restore_window_button)
        self.close_window_button = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_window_button.sizePolicy().hasHeightForWidth())
        self.close_window_button.setSizePolicy(sizePolicy)
        self.close_window_button.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    padding: 5px 5px 5px 5px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgba(255, 0,0, 200);\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 5px 5px 5px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgba(255, 100, 100, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 5px 5px 5px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgba(255, 60, 60, 200);\n"
"}")
        self.close_window_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/window/icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_window_button.setIcon(icon3)
        self.close_window_button.setObjectName("close_window_button")
        self.horizontalLayout_2.addWidget(self.close_window_button)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.toolbox_frame = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbox_frame.sizePolicy().hasHeightForWidth())
        self.toolbox_frame.setSizePolicy(sizePolicy)
        self.toolbox_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.toolbox_frame.setMaximumSize(QtCore.QSize(255, 16777215))
        self.toolbox_frame.setBaseSize(QtCore.QSize(0, 0))
        self.toolbox_frame.setStyleSheet("#toolbox_frame {\n"
"    background-image: url(:/background-image/icons/background);\n"
"}")
        self.toolbox_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolbox_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolbox_frame.setObjectName("toolbox_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.toolbox_frame)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_5 = QtWidgets.QFrame(self.toolbox_frame)
        self.frame_5.setMinimumSize(QtCore.QSize(253, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.toolBox = QtWidgets.QToolBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("QToolBox{\n"
"    text-align: left;\n"
"}\n"
"QToolBox::tab {\n"
"    border-radius: 5px;\n"
"    color: rgb(77, 77, 77);\n"
"    background-color: rgba(130, 130, 130, 100);\n"
"    text-align: left;\n"
"}\n"
"")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 253, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page.sizePolicy().hasHeightForWidth())
        self.page.setSizePolicy(sizePolicy)
        self.page.setStyleSheet("background-color: rgba(255, 255, 255, 30);")
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.page)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(150, 150, 150);\n"
"    border-bottom: 5px solid rgb(150, 150, 150);\n"
"    background-color: rgba(100, 100, 100, 200);\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(190, 190, 190);\n"
"    border-bottom: 5px solid rgb(190, 190, 190);\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(100, 100, 100);\n"
"    border-bottom: 5px solid rgb(100, 100, 100);\n"
"    background-color: rgba(60, 60, 60, 200);\n"
"}")
        self.pushButton_9.setDefault(False)
        self.pushButton_9.setFlat(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/toolbox_icons/icons/arrow_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page, icon4, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 253, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_2.sizePolicy().hasHeightForWidth())
        self.page_2.setSizePolicy(sizePolicy)
        self.page_2.setStyleSheet("background-color: rgba(255, 255, 255, 30);")
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_13 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(150, 150, 150);\n"
"    border-bottom: 5px solid rgb(150, 150, 150);\n"
"    background-color: rgba(100, 100, 100, 200);\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(190, 190, 190);\n"
"    border-bottom: 5px solid rgb(190, 190, 190);\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(100, 100, 100);\n"
"    border-bottom: 5px solid rgb(100, 100, 100);\n"
"    background-color: rgba(60, 60, 60, 200);\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_3.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(150, 150, 150);\n"
"    border-bottom: 5px solid rgb(150, 150, 150);\n"
"    background-color: rgba(100, 100, 100, 200);\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(190, 190, 190);\n"
"    border-bottom: 5px solid rgb(190, 190, 190);\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(100, 100, 100);\n"
"    border-bottom: 5px solid rgb(100, 100, 100);\n"
"    background-color: rgba(60, 60, 60, 200);\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_3.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(150, 150, 150);\n"
"    border-bottom: 5px solid rgb(150, 150, 150);\n"
"    background-color: rgba(100, 100, 100, 200);\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(190, 190, 190);\n"
"    border-bottom: 5px solid rgb(190, 190, 190);\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    border-right: 2px solid rgb(100, 100, 100);\n"
"    border-bottom: 5px solid rgb(100, 100, 100);\n"
"    background-color: rgba(60, 60, 60, 200);\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_3.addWidget(self.pushButton_15)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/toolbox_icons/icons/arrow_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_2, icon5, "")
        self.verticalLayout_11.addWidget(self.toolBox)
        self.verticalLayout_10.addWidget(self.frame_5)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.toolbox_frame)
        self.apps_grid = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apps_grid.sizePolicy().hasHeightForWidth())
        self.apps_grid.setSizePolicy(sizePolicy)
        self.apps_grid.setMinimumSize(QtCore.QSize(700, 0))
        self.apps_grid.setStyleSheet("#apps_grid {\n"
"    background-image: url(:/background-image/icons/background);\n"
"}")
        self.apps_grid.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.apps_grid.setFrameShadow(QtWidgets.QFrame.Raised)
        self.apps_grid.setObjectName("apps_grid")
        self.gridLayout = QtWidgets.QGridLayout(self.apps_grid)
        self.gridLayout.setContentsMargins(15, 15, 15, 15)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.grafana_frame = QtWidgets.QFrame(self.apps_grid)
        self.grafana_frame.setStyleSheet("background-color: none")
        self.grafana_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.grafana_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.grafana_frame.setObjectName("grafana_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.grafana_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.grafana_btn = QtWidgets.QPushButton(self.grafana_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grafana_btn.sizePolicy().hasHeightForWidth())
        self.grafana_btn.setSizePolicy(sizePolicy)
        self.grafana_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    background-color: rgba(60, 60, 60, 200);\n"
"}")
        self.grafana_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/app_icons/icons/Grafana.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.grafana_btn.setIcon(icon6)
        self.grafana_btn.setIconSize(QtCore.QSize(100, 100))
        self.grafana_btn.setShortcut("")
        self.grafana_btn.setAutoDefault(False)
        self.grafana_btn.setDefault(False)
        self.grafana_btn.setFlat(False)
        self.grafana_btn.setObjectName("grafana_btn")
        self.verticalLayout_4.addWidget(self.grafana_btn)
        self.grafana_label = QtWidgets.QLabel(self.grafana_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grafana_label.sizePolicy().hasHeightForWidth())
        self.grafana_label.setSizePolicy(sizePolicy)
        self.grafana_label.setStyleSheet("color: rgb(72, 72, 72);")
        self.grafana_label.setAlignment(QtCore.Qt.AlignCenter)
        self.grafana_label.setObjectName("grafana_label")
        self.verticalLayout_4.addWidget(self.grafana_label)
        self.gridLayout.addWidget(self.grafana_frame, 0, 0, 1, 1)
        self.nifi_frame = QtWidgets.QFrame(self.apps_grid)
        self.nifi_frame.setStyleSheet("background-color: none")
        self.nifi_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.nifi_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nifi_frame.setObjectName("nifi_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.nifi_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.nifi_btn = QtWidgets.QPushButton(self.nifi_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nifi_btn.sizePolicy().hasHeightForWidth())
        self.nifi_btn.setSizePolicy(sizePolicy)
        self.nifi_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    background-color: rgba(60, 60, 60, 200);\n"
"}")
        self.nifi_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/app_icons/icons/nifi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nifi_btn.setIcon(icon7)
        self.nifi_btn.setIconSize(QtCore.QSize(100, 100))
        self.nifi_btn.setFlat(False)
        self.nifi_btn.setObjectName("nifi_btn")
        self.verticalLayout_5.addWidget(self.nifi_btn)
        self.nifi_label = QtWidgets.QLabel(self.nifi_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nifi_label.sizePolicy().hasHeightForWidth())
        self.nifi_label.setSizePolicy(sizePolicy)
        self.nifi_label.setStyleSheet("color: rgb(72, 72, 72);")
        self.nifi_label.setAlignment(QtCore.Qt.AlignCenter)
        self.nifi_label.setObjectName("nifi_label")
        self.verticalLayout_5.addWidget(self.nifi_label)
        self.gridLayout.addWidget(self.nifi_frame, 0, 1, 1, 1)
        self.airflow_frame = QtWidgets.QFrame(self.apps_grid)
        self.airflow_frame.setStyleSheet("background-color: none")
        self.airflow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.airflow_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.airflow_frame.setObjectName("airflow_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.airflow_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.airflow_btn = QtWidgets.QPushButton(self.airflow_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.airflow_btn.sizePolicy().hasHeightForWidth())
        self.airflow_btn.setSizePolicy(sizePolicy)
        self.airflow_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    background-color: rgba(60, 60, 60, 200);\n"
"}")
        self.airflow_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/app_icons/icons/airflow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.airflow_btn.setIcon(icon8)
        self.airflow_btn.setIconSize(QtCore.QSize(100, 100))
        self.airflow_btn.setFlat(False)
        self.airflow_btn.setObjectName("airflow_btn")
        self.verticalLayout_6.addWidget(self.airflow_btn)
        self.airflow_label = QtWidgets.QLabel(self.airflow_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.airflow_label.sizePolicy().hasHeightForWidth())
        self.airflow_label.setSizePolicy(sizePolicy)
        self.airflow_label.setStyleSheet("color: rgb(72, 72, 72);")
        self.airflow_label.setAlignment(QtCore.Qt.AlignCenter)
        self.airflow_label.setObjectName("airflow_label")
        self.verticalLayout_6.addWidget(self.airflow_label)
        self.gridLayout.addWidget(self.airflow_frame, 0, 2, 1, 1)
        self.schema_reg_frame = QtWidgets.QFrame(self.apps_grid)
        self.schema_reg_frame.setStyleSheet("background-color: none")
        self.schema_reg_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.schema_reg_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.schema_reg_frame.setObjectName("schema_reg_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.schema_reg_frame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.schema_reg_btn = QtWidgets.QPushButton(self.schema_reg_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schema_reg_btn.sizePolicy().hasHeightForWidth())
        self.schema_reg_btn.setSizePolicy(sizePolicy)
        self.schema_reg_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    background-color: rgba(60, 60, 60, 200);\n"
"}")
        self.schema_reg_btn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/app_icons/icons/schema_registry.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.schema_reg_btn.setIcon(icon9)
        self.schema_reg_btn.setIconSize(QtCore.QSize(100, 100))
        self.schema_reg_btn.setFlat(False)
        self.schema_reg_btn.setObjectName("schema_reg_btn")
        self.verticalLayout_7.addWidget(self.schema_reg_btn)
        self.schema_reg_label = QtWidgets.QLabel(self.schema_reg_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schema_reg_label.sizePolicy().hasHeightForWidth())
        self.schema_reg_label.setSizePolicy(sizePolicy)
        self.schema_reg_label.setStyleSheet("color: rgb(72, 72, 72);")
        self.schema_reg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.schema_reg_label.setObjectName("schema_reg_label")
        self.verticalLayout_7.addWidget(self.schema_reg_label)
        self.gridLayout.addWidget(self.schema_reg_frame, 1, 0, 1, 1)
        self.schema_reg_ui_frame = QtWidgets.QFrame(self.apps_grid)
        self.schema_reg_ui_frame.setStyleSheet("background-color: none")
        self.schema_reg_ui_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.schema_reg_ui_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.schema_reg_ui_frame.setObjectName("schema_reg_ui_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.schema_reg_ui_frame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.schema_reg_ui_btn = QtWidgets.QPushButton(self.schema_reg_ui_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schema_reg_ui_btn.sizePolicy().hasHeightForWidth())
        self.schema_reg_ui_btn.setSizePolicy(sizePolicy)
        self.schema_reg_ui_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    background-color: rgba(60, 60, 60, 200);\n"
"}")
        self.schema_reg_ui_btn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/app_icons/icons/schema_registry_ui.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.schema_reg_ui_btn.setIcon(icon10)
        self.schema_reg_ui_btn.setIconSize(QtCore.QSize(100, 100))
        self.schema_reg_ui_btn.setFlat(False)
        self.schema_reg_ui_btn.setObjectName("schema_reg_ui_btn")
        self.verticalLayout_8.addWidget(self.schema_reg_ui_btn)
        self.schema_reg_ui_label = QtWidgets.QLabel(self.schema_reg_ui_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schema_reg_ui_label.sizePolicy().hasHeightForWidth())
        self.schema_reg_ui_label.setSizePolicy(sizePolicy)
        self.schema_reg_ui_label.setStyleSheet("color: rgb(72, 72, 72);")
        self.schema_reg_ui_label.setAlignment(QtCore.Qt.AlignCenter)
        self.schema_reg_ui_label.setObjectName("schema_reg_ui_label")
        self.verticalLayout_8.addWidget(self.schema_reg_ui_label)
        self.gridLayout.addWidget(self.schema_reg_ui_frame, 1, 1, 1, 1)
        self.offset_explorer_frame = QtWidgets.QFrame(self.apps_grid)
        self.offset_explorer_frame.setStyleSheet("background-color: none")
        self.offset_explorer_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.offset_explorer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.offset_explorer_frame.setObjectName("offset_explorer_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.offset_explorer_frame)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.offset_explorer_btn = QtWidgets.QPushButton(self.offset_explorer_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offset_explorer_btn.sizePolicy().hasHeightForWidth())
        self.offset_explorer_btn.setSizePolicy(sizePolicy)
        self.offset_explorer_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none\n"
"}\n"
"QPushButton::hover {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    background-color: rgba(140, 140, 140, 200);\n"
"}\n"
"QPushButton::pressed {\n"
"    color: black;\n"
"    padding: 5px 35px 5px 35px;\n"
"    margin: 2px 1px 2px 1px;\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    background-color: rgba(60, 60, 60, 200);\n"
"}")
        self.offset_explorer_btn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/app_icons/icons/offset_explorer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.offset_explorer_btn.setIcon(icon11)
        self.offset_explorer_btn.setIconSize(QtCore.QSize(100, 100))
        self.offset_explorer_btn.setFlat(False)
        self.offset_explorer_btn.setObjectName("offset_explorer_btn")
        self.verticalLayout_9.addWidget(self.offset_explorer_btn)
        self.offset_explorer_label = QtWidgets.QLabel(self.offset_explorer_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offset_explorer_label.sizePolicy().hasHeightForWidth())
        self.offset_explorer_label.setSizePolicy(sizePolicy)
        self.offset_explorer_label.setStyleSheet("color: rgb(72, 72, 72);")
        self.offset_explorer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.offset_explorer_label.setObjectName("offset_explorer_label")
        self.verticalLayout_9.addWidget(self.offset_explorer_label)
        self.gridLayout.addWidget(self.offset_explorer_frame, 1, 2, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.apps_grid)
        self.verticalLayout.addWidget(self.frame_2)
        self.bar_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bar_frame.sizePolicy().hasHeightForWidth())
        self.bar_frame.setSizePolicy(sizePolicy)
        self.bar_frame.setStyleSheet("#bar_frame {\n"
"    background-image: url(:/background-image/icons/background);\n"
"}")
        self.bar_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bar_frame.setObjectName("bar_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.bar_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.progressBar = QtWidgets.QProgressBar(self.bar_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setStyleSheet("QProgressBar {\n"
" background-color: #C0C6CA;\n"
" color: black;\n"
" border: 0px;\n"
" padding: 0px;\n"
" height: 20;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(165, 173, 165, 255), stop:0.987903 rgba(90, 90, 90, 255), stop:0.991935 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    width: 3px\n"
"}")
        self.progressBar.setProperty("value", 100)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_7.addWidget(self.progressBar)
        self.process = QtWidgets.QLabel(self.bar_frame)
        self.process.setStyleSheet("color: rgb(72, 72, 72);")
        self.process.setObjectName("process")
        self.horizontalLayout_7.addWidget(self.process)
        self.verticalLayout.addWidget(self.bar_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Меню управления вот этим всем"))
        self.pushButton_7.setText(_translate("MainWindow", "Главная"))
        self.pushButton_4.setText(_translate("MainWindow", "Админка"))
        self.pushButton_5.setText(_translate("MainWindow", "Информация"))
        self.pushButton_6.setText(_translate("MainWindow", "Мои контакты"))
        self.pushButton_9.setText(_translate("MainWindow", "Запуск / Рестарт"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Запуск контейнеров"))
        self.pushButton_13.setText(_translate("MainWindow", "Удалить контейнеры"))
        self.pushButton_14.setText(_translate("MainWindow", "Стереть volumes"))
        self.pushButton_15.setText(_translate("MainWindow", "Стереть networks"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Сброс"))
        self.grafana_label.setText(_translate("MainWindow", "Grafana"))
        self.nifi_label.setText(_translate("MainWindow", "Nifi"))
        self.airflow_label.setText(_translate("MainWindow", "Airflow"))
        self.schema_reg_label.setText(_translate("MainWindow", "Schema registry"))
        self.schema_reg_ui_label.setText(_translate("MainWindow", "Schema registry UI"))
        self.offset_explorer_label.setText(_translate("MainWindow", "Offset Explorer"))
        self.process.setText(_translate("MainWindow", "     Ход работы     "))
from . import resource_rc

